[tool.poetry]
name = "trivia"
version = "0.1.0"
description = "Terminal Trivia Game"
authors = ["Kyle Negley"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.24.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
